version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: stocksage
      runtime: python
      repo: https://github.com/opslash/stocksage
      plan: free
      envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn -c gunicorn.conf.py main:app
      autoDeployTrigger: commit
