services:
  - type: web
    name: stocksage
    env: docker
    repo: https://github.com/opslash/stocksage
    plan: free
    region: oregon
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
